import os
import json
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def get_llm_score(text: str) -> dict:
    """
    Signal 1: LLM-based classification using Groq.

    Sends the text to the Groq model and asks it to assess whether
    the writing reads as AI-generated or human-written.

    Returns a dict like:
    {
        "llm_score": 0.81,   # 0 = very human-like, 1 = very AI-like
        "reasoning": "short explanation from the model"
    }
    """
    prompt = f"""You are an AI content detector. Analyze the following text and
estimate the probability that it was generated by an AI rather than written by a human.

Respond with ONLY a JSON object in this exact format, no other text:
{{"llm_score": <float between 0 and 1>, "reasoning": "<one sentence explanation>"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )

    raw_output = response.choices[0].message.content.strip()

    # Strip markdown code fences if the model adds them anyway
    if raw_output.startswith("```"):
        raw_output = raw_output.strip("`")
        if raw_output.startswith("json"):
            raw_output = raw_output[4:]
        raw_output = raw_output.strip()

    try:
        parsed = json.loads(raw_output)
        score = float(parsed.get("llm_score", 0.5))
        reasoning = parsed.get("reasoning", "")
    except (json.JSONDecodeError, ValueError):
        # Fallback if the model didn't return valid JSON
        score = 0.5
        reasoning = "Could not parse model output; defaulted to uncertain."

    # Clamp score to [0, 1] just in case
    score = max(0.0, min(1.0, score))

    return {"llm_score": score, "reasoning": reasoning}


if __name__ == "__main__":
    # Quick manual test - run with: python detection.py
    test_human = "I spilled coffee on my keyboard this morning and now the 'e' key sticks. Typing has become a small daily annoyance."
    test_ai = "The implementation of artificial intelligence systems necessitates careful consideration of multiple interdependent factors, including but not limited to scalability, robustness, and ethical implications."

    print("Human-like text:", get_llm_score(test_human))
    print("AI-like text:", get_llm_score(test_ai))