import os
import json
import re
import math
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


# ─────────────────────────────────────────
# Signal 1: Groq LLM Classification
# ─────────────────────────────────────────

def get_llm_score(text: str) -> dict:
    """
    Signal 1: LLM-based classification using Groq.
    Returns a dict with llm_score (0=human, 1=AI) and reasoning.
    """
    prompt = f"""You are an AI content detector. Analyze the following text and
estimate the probability that it was generated by an AI rather than written by a human.

Respond with ONLY a JSON object in this exact format, no other text:
{{"llm_score": <float between 0 and 1>, "reasoning": "<one sentence explanation>"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )

    raw_output = response.choices[0].message.content.strip()

    if raw_output.startswith("```"):
        raw_output = raw_output.strip("`")
        if raw_output.startswith("json"):
            raw_output = raw_output[4:]
        raw_output = raw_output.strip()

    try:
        parsed = json.loads(raw_output)
        score = float(parsed.get("llm_score", 0.5))
        reasoning = parsed.get("reasoning", "")
    except (json.JSONDecodeError, ValueError):
        score = 0.5
        reasoning = "Could not parse model output; defaulted to uncertain."

    score = max(0.0, min(1.0, score))
    return {"llm_score": score, "reasoning": reasoning}


# ─────────────────────────────────────────
# Signal 2: Stylometric Heuristics
# ─────────────────────────────────────────

def get_stylometric_score(text: str) -> dict:
    """
    Signal 2: Stylometric heuristics computed in pure Python.

    Measures 3 properties:
    - Sentence length variance (AI = low variance = uniform sentence lengths)
    - Type-token ratio (AI = lower TTR = less vocabulary diversity)
    - Punctuation density (AI = lower = fewer commas, dashes, etc.)

    Returns a dict with stylometric_score (0=human, 1=AI) and sub-scores.
    """
    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # Split into words
    words = re.findall(r'\b\w+\b', text.lower())

    if len(words) < 10 or len(sentences) < 2:
        # Not enough text to score reliably — return uncertain
        return {
            "stylometric_score": 0.5,
            "sentence_variance_score": 0.5,
            "ttr_score": 0.5,
            "punctuation_score": 0.5,
            "note": "Text too short for reliable stylometric analysis"
        }

    # ── Metric 1: Sentence length variance ──
    # AI text tends to have uniform sentence lengths (low variance)
    sentence_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    mean_len = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    std_dev = math.sqrt(variance)

    # Normalize: std_dev of ~8+ words = very human-like (0.0), ~0-2 = AI-like (1.0)
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # ── Metric 2: Type-Token Ratio (vocabulary diversity) ──
    # AI text tends to reuse words more (lower TTR)
    unique_words = set(words)
    ttr = len(unique_words) / len(words)

    # Normalize: TTR of 0.8+ = very human (0.0), TTR of 0.4 or below = AI-like (1.0)
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.4) / 0.4)))

    # ── Metric 3: Punctuation density ──
    # Human writing uses more varied punctuation (commas, dashes, colons, etc.)
    punct_chars = re.findall(r'[,;:—\-"\'()]', text)
    punct_density = len(punct_chars) / len(words)

    # Normalize: density of 0.15+ = human-like (0.0), 0.03 or below = AI-like (1.0)
    punctuation_score = max(0.0, min(1.0, 1.0 - ((punct_density - 0.03) / 0.12)))

    # ── Combine the 3 metrics (equal weight) ──
    stylometric_score = (variance_score + ttr_score + punctuation_score) / 3.0
    stylometric_score = max(0.0, min(1.0, stylometric_score))

    return {
        "stylometric_score": round(stylometric_score, 3),
        "sentence_variance_score": round(variance_score, 3),
        "ttr_score": round(ttr_score, 3),
        "punctuation_score": round(punctuation_score, 3),
    }


# ─────────────────────────────────────────
# Confidence Scoring (combines both signals)
# ─────────────────────────────────────────

def compute_confidence(llm_score: float, stylometric_score: float) -> dict:
    """
    Combines Signal 1 (60%) and Signal 2 (40%) into a single confidence score.
    Maps score to a verdict and label text per planning.md thresholds.
    """
    combined = round((0.6 * llm_score) + (0.4 * stylometric_score), 3)

    if combined >= 0.85:
        verdict = "likely_ai"
        label = "This content shows strong indicators of AI generation. Our system is highly confident this was not written entirely by a human."
    elif combined >= 0.60:
        verdict = "likely_ai"
        label = "This content shows several indicators of AI generation, though our confidence is moderate. Consider this result alongside other context."
    elif combined >= 0.40:
        verdict = "uncertain"
        label = "We could not confidently determine whether this content was AI-generated or human-written. The available evidence is mixed, so this result should be interpreted cautiously."
    elif combined >= 0.16:
        verdict = "likely_human"
        label = "This content shows several indicators of human authorship, though our confidence is moderate. Consider this result alongside other context."
    else:
        verdict = "likely_human"
        label = "This content shows strong indicators of human authorship. Our system found little evidence of AI generation."

    return {
        "combined_score": combined,
        "verdict": verdict,
        "label": label,
    }


# ─────────────────────────────────────────
# Manual test — run with: python detection.py
# ─────────────────────────────────────────

if __name__ == "__main__":
    tests = {
        "Clearly AI": "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications. Furthermore, stakeholders across various sectors must collaborate to ensure responsible deployment.",
        "Clearly Human": "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it and i was thirsty for like three hours after. my friend got the spicy version and said it was better. probably won't go back unless someone drags me there",
        "Borderline Formal": "The relationship between monetary policy and asset price inflation has been extensively studied in the literature. Central banks face a fundamental tension between their mandate for price stability and the unintended consequences of prolonged low interest rates on equity and real estate valuations.",
        "Borderline Edited AI": "I've been thinking a lot about remote work lately. There are genuine tradeoffs — flexibility and no commute on one side, isolation and blurred work-life boundaries on the other. Studies show productivity varies widely by individual and role type.",
    }

    for label, text in tests.items():
        s1 = get_llm_score(text)
        s2 = get_stylometric_score(text)
        result = compute_confidence(s1["llm_score"], s2["stylometric_score"])
        print(f"\n── {label} ──")
        print(f"  LLM score:         {s1['llm_score']}")
        print(f"  Stylometric score: {s2['stylometric_score']}")
        print(f"  Combined:          {result['combined_score']}")
        print(f"  Verdict:           {result['verdict']}")